Ошибка: HTTPConnectionPool(host='121', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002027ABC4DF0>: Failed to resolve '121' ([Errno 11001] getaddrinfo failed)"))