Ошибка: HTTPConnectionPool(host='140', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x0000020276543B50>: Failed to resolve '140' ([Errno 11001] getaddrinfo failed)"))