Ошибка: HTTPConnectionPool(host='143', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002027AB1B9D0>: Failed to resolve '143' ([Errno 11001] getaddrinfo failed)"))