Ошибка: HTTPConnectionPool(host='149', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002027AB1B2E0>: Failed to resolve '149' ([Errno 11001] getaddrinfo failed)"))