Ошибка: HTTPConnectionPool(host='22', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002027AB499F0>: Failed to resolve '22' ([Errno 11001] getaddrinfo failed)"))