Ошибка: HTTPConnectionPool(host='27', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002027AB93FD0>: Failed to resolve '27' ([Errno 11001] getaddrinfo failed)"))