Ошибка: HTTPConnectionPool(host='43', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002027AB48E50>: Failed to resolve '43' ([Errno 11001] getaddrinfo failed)"))