Ошибка: HTTPConnectionPool(host='44', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002027AB4A710>: Failed to resolve '44' ([Errno 11001] getaddrinfo failed)"))