Ошибка: HTTPConnectionPool(host='5', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002027AB18070>: Failed to resolve '5' ([Errno 11001] getaddrinfo failed)"))