Ошибка: HTTPConnectionPool(host='79', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x00000202765424D0>: Failed to resolve '79' ([Errno 11001] getaddrinfo failed)"))