Ошибка: HTTPConnectionPool(host='89', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002027AB4AB00>: Failed to resolve '89' ([Errno 11001] getaddrinfo failed)"))