Ошибка: HTTPConnectionPool(host='94', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002027AAE4E80>: Failed to resolve '94' ([Errno 11001] getaddrinfo failed)"))