Ошибка: HTTPConnectionPool(host='a', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x00000161C0131630>: Failed to resolve 'a' ([Errno 11001] getaddrinfo failed)"))
URL: http://a