Ошибка: HTTPConnectionPool(host='cloudfront.net', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002C3934282B0>: Failed to resolve 'cloudfront.net' ([Errno 11001] getaddrinfo failed)"))