Ошибка: HTTPConnectionPool(host='i', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x00000161C50366E0>: Failed to resolve 'i' ([Errno 11001] getaddrinfo failed)"))
URL: http://i