Ошибка: HTTPConnectionPool(host='u', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x00000161C4FFF8E0>: Failed to resolve 'u' ([Errno 11001] getaddrinfo failed)"))
URL: http://u