Ошибка: HTTPConnectionPool(host='upcbroadband.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002C396204A60>: Failed to resolve 'upcbroadband.com' ([Errno 11001] getaddrinfo failed)"))